### ISSUE TITLE
Add support for custom statuses

### ISSUE THREAD

**Issue by ayancey** [LordBoos/discord_game#4]
Hi,

Now that discord has custom statuses, this would be a really incredible addition to this plugin.

Thanks,
Alex

**Comment by LordBoos** [comment]
Hello, 

thanks for you suggestion. 

Unfortunately this is impossible right now because of two things:
Discord issue: https://github.com/discordapp/discord-api-docs/issues/1160
Discord.py: https://github.com/Rapptz/discord.py/issues/2400

Once those issues are resolved I can add support to this component.

**Comment by ayancey** [comment]
Thank you, keep up the good work on this project

**Comment by LordBoos** [comment]
Custom statuses support added in version 3.0.0, commit https://github.com/LordBoos/discord_game/commit/673bb9876c2054cfe64b11f6aa3fc5bd9cfbe2dc
