### ISSUE TITLE
Integration 'discord_game' not found

### ISSUE THREAD

**Issue by darkkatarsis** [LordBoos/discord_game#44]
After updating home assistant to version 2022.3, and updating integration to version 4.2.4/5.0.0.alpha1 this error appears:
`Failed to call service homeassistant/restart. The system cannot restart because the configuration is not valid: Platform error sensor.discord_game - Integration 'discord_game' not found.`. I was already trying first update integration and after that add sensor - but it turns out that's not the problem here

**Comment by kj4lxc** [comment]
I had the same thing happen to me.  Go into your config file and comment out all the lines for your discord_game config, restart home assistant, then uncomment those lines and restart it again.  Thats all I had to do.  Look like HA gets confused sometimes enabling the integration and it just needs a restart but the safety built into the config checker wont let it, or if its the first time the plugin is installed you have to do the above anyway because of the same safety check thing.

**Comment by LordBoos** [comment]
Yea HA is behaving weirdly in this situation. You have multiple options:

- suggestion from @kj4lxc 
- hard rebooting your HA server
- rebooting HOST from supervisor
- restarting HA core from SSH console (looks like this skips the config verification)

**Comment by darkkatarsis** [comment]
uninstall and install one more time works fine
